module ActionSyncData
{
  struct Ready
  {
    string actor_name;
    string graph_name;
    unsigned long long timestamp;
  };

  struct Waitable
  {
    string actor_name;
    string action_name;
    string graph_name;
  };

  struct Notification
  {
    string actor_name;
    string parameters;
    Waitable waitable;
  };
};
