module ActionSyncData
{
  struct NameStamped
  {
    string actor_name;
    unsigned long long timestamp;
  };

  struct Handshake
  {
    string actor_name;
    string handshake_token;
    unsigned long long timestamp;
    sequence<NameStamped> other_actors;
  };

  struct Waitable
  {
    string actor_name;
    string action_name;
    string graph_name;
  };

  struct Notification
  {
    string parameters;
    string result;
    string notification_id;
    Waitable waitable;
  };
};
